create database SampleDBANS
use SampleDBANS
DROP DATABASE SampleDBANS

CREATE TABLE USERS
(
USER_ID int identity(1,1) PRIMARY KEY,
USER_LASTNAME varchar(50) NOT NULL,
USER_FIRSTNAME varchar(50) NOT NULL,
USER_MIDDLENAME varchar(50) ,
USER_POSITIONID INT FOREIGN KEY REFERENCES USERPOSITION(USER_POSITIONID),
USER_USERNAME varchar(50) NOT NULL,
USER_PASSWORD varchar(50) NOT NULL,
USER_CONTACT varchar(50) NOT NULL,
ISACTIVE BIT DEFAULT 1,
USER_DATEADDED DATE DEFAULT GETDATE(),
USER_CREATOR varchar(50) NOT NULL
)

CREATE TABLE USERPOSITION
(
USER_POSITIONID INT IDENTITY(1,1) PRIMARY KEY,
USER_POSITION varchar(50) NOT NULL,
USER_DESCRIPTION VARCHAR(50) NOT NULL,
ISACTIVE BIT DEFAULT 1
)

CREATE TABLE STUDENT
(
ST_ID int identity(1,1) PRIMARY KEY NOT NULL,
ST_FIRSTNAME VARCHAR(50) NOT NULL,
ST_MIDDLENAME VARCHAR(50),
ST_LASTNAME VARCHAR(50) NOT NULL,
ST_YEARLEVEL VARCHAR(50) NOT NULL,
ST_SCHOOLYEAR VARCHAR(50) NOT NULL,
ST_BIRTHDATE DATE NOT NULL,
ST_AGE INT NOT NULL,
ST_BIRTHPLACE VARCHAR(50) NOT NULL,	
ST_ADDRESS VARCHAR(50) NOT NULL,
ST_GENDER VARCHAR(50) NOT NULL,
ST_CONTACTNUMBER VARCHAR(50),
ISACTIVE BIT,
ST_HEIGHT DECIMAL NOT NULL,
ST_WEIGHT DECIMAL NOT NULL,
ST_BLOODPRESSURE INT NOT NULL,
P_ID INT FOREIGN KEY REFERENCES PARENT(P_ID),
SEC_ID INT FOREIGN KEY REFERENCES SECTION(SEC_ID)
)

CREATE TABLE PARENT 
(
P_ID INT IDENTITY(1,1) PRIMARY KEY,
P_NAME VARCHAR(50) NOT NULL,
P_CONTACT VARCHAR(50) NOT NULL,
P_OCCUPATION VARCHAR(50) NOT NULL,
P_TYPE VARCHAR(50) NOT NULL
)

CREATE TABLE GRADE
(
GRADE_ID INT IDENTITY(1,1) PRIMARY KEY,
ST_ID INT FOREIGN KEY REFERENCES STUDENT(ST_ID),
GRADEPERIOD VARCHAR(50) NOT NULL,
GRADE DECIMAL NOT NULL,
GRADESUBJECT VARCHAR(50) NOT NULL,
SUBJECT_ID INT FOREIGN KEY REFERENCES SUBJECT(SUBJECT_ID)
)

CREATE TABLE SUBJECT
(
SUBJECT_ID INT IDENTITY(1,1) PRIMARY KEY,
SUBJECT VARCHAR(50) NOT NULL
)

CREATE TABLE SECTIONSUBJECT
(
SECSUB_ID INT IDENTITY(1,1) PRIMARY KEY,
SUBJECT_ID INT  FOREIGN KEY REFERENCES SUBJECT(SUBJECT_ID),
SEC_ID INT  FOREIGN KEY REFERENCES SECTION(SEC_ID),
)

CREATE TABLE SECTION
(
SEC_ID INT IDENTITY(1,1) PRIMARY KEY,
SEC_NAME VARCHAR(50) NOT NULL,
SEC_CAPACITY INT NOT NULL
)

CREATE TABLE REQUIRMENTS
(
REQ_ID INT IDENTITY(1,1) PRIMARY KEY,
REQ_NAME VARCHAR(50) NOT NULL,
REQ_DETAILS VARCHAR(50) NOT NULL,
ST_ID INT FOREIGN KEY REFERENCES STUDENT(ST_ID),
REQ_ADDED DATETIME NOT NULL
)

CREATE TABLE BOOKS
(
B_ID INT IDENTITY(1,1) PRIMARY KEY,
B_BOOKNAME VARCHAR (50) NOT NULL,
B_YEARLEVEL VARCHAR (50) NOT NULL
)

CREATE TABLE PAYMENTDETAILS
(
PD_ID INT IDENTITY(1,1) PRIMARY KEY,
ST_ID INT FOREIGN KEY REFERENCES STUDENT(ST_ID),
PAYMENTDESC VARCHAR(50) NOT NULL,
PAYMENTAMOUNT MONEY NOT NULL
)

CREATE TABLE TEACHER
(
T_ID INT IDENTITY(1,1) PRIMARY KEY,
T_FIRSTNAME  VARCHAR(50) NOT NULL,
T_MIDDLENAME VARCHAR(50),
T_LASTNAME VARCHAR(50) NOT NULL,
T_GENDER VARCHAR(50) NOT NULL,
T_BIRTHDATE DATE NOT NULL,
ISACTIVE BIT,
T_CONTACTNUMBER VARCHAR(50) NOT NULL,
SEC_ID INT  FOREIGN KEY REFERENCES SECTION(SEC_ID),
)

CREATE TABLE TEACHERSECTION
(
TS_ID INT IDENTITY(1,1) PRIMARY KEY,
SECSUB_ID INT  FOREIGN KEY REFERENCES SECTION(SEC_ID)
)

CREATE TABLE TEACHERSCHEDULE
(
TSCHED_ID INT IDENTITY(1,1) PRIMARY KEY,
TS_ID INT FOREIGN KEY REFERENCES TEACHERSECTION(TS_ID),
TIMESTART TIME NOT NULL,
TIMEEND TIME NOT NULL
)

